### ISSUE TITLE
Flag not displaying

### ISSUE THREAD

**Issue by darko-nimbus** [KevzPeter/Duolingo-Stats-Card#1]
Hello Peter, 

First of all: great stats card! I just added it to my profile overview. 

I noticed that for one of the three languages I'm studying (Dutch, in the middle) it doesn't show the flag but a little golden map section.

Screenshot:  

![image](https://github.com/KevzPeter/Duolingo-Stats-Card/assets/144227582/d9f19ddb-01c6-40cb-83d1-86faef448264)

**Comment by KevzPeter** [comment]
Hey @darko-nimbus 

Thanks for bringing up this bug. It seems Duolingo has a different language code for Dutch ("nl-NL") compared to [ISO 639 standard](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes) ("nl")

I've updated the code to display the correct flag
