### ISSUE TITLE
A missing language `German`

### ISSUE THREAD

**Issue by iltafah** [KevzPeter/Duolingo-Stats-Card#4]
Hello there

There is a problem that I noticed within this amazing stats card, and it is as follows, as you can see I have 4 languages that I practice using Duolingo, and the first one is German, but only the other three are showing up in my stats card:

<img width="476" alt="Screen Shot 2024-02-24 at 11 15 57 PM" src="https://github.com/KevzPeter/Duolingo-Stats-Card/assets/56886719/dc0fcf50-a21b-4422-945e-ee3085d0a1bc">

<img width="436" alt="Screen Shot 2024-02-24 at 11 16 39 PM" src="https://github.com/KevzPeter/Duolingo-Stats-Card/assets/56886719/fd4f95b1-c9fb-4c08-9c6a-667f63b9c3c9">

**Comment by iltafah** [comment]
I deleted the Arabic language `the green one` and the German appeared, but not sure why it doesn't show in the middle since I have the highest score on it
<img width="436" alt="Screen Shot 2024-02-24 at 11 42 38 PM" src="https://github.com/KevzPeter/Duolingo-Stats-Card/assets/56886719/2701c36c-d573-4c4b-b669-8daf30b7742b">

**Comment by KevzPeter** [comment]
Hey @iltafah

The stats card works by filtering your **top 3 languages** based on the number of **_crowns_** you've earned in each course, and displays them from **left to right**.

You can earn XP through timed challenges, speaking exercises etc. that **don't necessarily progress your skill path** (i.e, unlocking crowns).
So some users may have a lot of crowns and less XP for a particular course, or few crowns and A LOT of XP (_German_ in your case).

I'll update the README page to make it clearer on what basis the languages are displayed. 

Would you like XP based filtering instead ? I can tweak the code to accept a query param from the user

**Comment by iltafah** [comment]
Ah got it, that would be great if you added this feature so the user can either show it based on XP or number of crowns.
Thaks for the answer much appreciated.

**Comment by KevzPeter** [comment]
I've added XP based sorting, just add a "sort" parameter to the end. 
eg: `![Duolingo Stats](https://duolingo-stats-card.vercel.app/api?id=23141883&sort=xp)`

You can try it out!

**Comment by iltafah** [comment]
@KevzPeter  Amazing, now it shows the progress based on XP

<img width="436" alt="Screen Shot 2024-02-25 at 6 40 48 PM" src="https://github.com/KevzPeter/Duolingo-Stats-Card/assets/56886719/1b444f70-f01e-479e-a8aa-cfff674d85fc">
