### ISSUE TITLE
Flags don't have straight edges

### ISSUE THREAD

**Issue by jannikgohr** [KevzPeter/Duolingo-Stats-Card#9]
I noticed that the flags don't have straight edges.
![logo_0002_fr](https://github.com/user-attachments/assets/f18e1eb2-26a2-4400-a9f4-b2d505b48f08)
![logo_0000_en](https://github.com/user-attachments/assets/3d002fbf-6242-4719-8fde-c0fea6f95af6)

Is this intentional?
All other assets have perfectly straight edges.

If this is not intentional, I might replace them with the original SVG files Duolingo uses [here](https://d35aaqx5ub95lt.cloudfront.net/vendor/87938207afff1598611ba626a8c4827c.svg).

**Comment by KevzPeter** [comment]
No it wasn't intentional, some of the images turned out weird while I converted them from png to svg. You can go ahead and replace them!
